### ISSUE TITLE
target-version is not read from config file

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/septentrion#21]
Because config file only sets defaults values, and target-version is `required=True`, setting target-version in `septentrion.ini` results in `Error: Missing option "--target-version".`

**Comment by samuelhamard** [comment]
@ewjoachim all settings are now geted from the setting_file so i think we could close this issue. (cf https://github.com/peopledoc/septentrion/blob/master/septentrion/configuration.py#L63)

**Comment by ewjoachim** [comment]
yep. Note that I'm not sure target *should* be read from config file in the first place, and not passed as command line argument of migrate.
