### ISSUE TITLE
Use Version objects all the way up

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/septentrion#47]
This deserves a discussion, I'm not sure about it.

We now have `Version` objects, but they're currently used only when comparing versions, etc. The rest of the stack passes versions as strings.
I guess it would be interesting to use `Version` objects all the way in the stack.

Pros:
- We currently parse them several times (but this is negligable computation time)
- There would be less ambiguity regarding the type expected for version arguments (but we have type annotations anyway)
- Bugs where we pass a string that is not a proper version would not be possible, thanks to static typing

Cons:
- We'd have to import the `Version` type everywhere, including in the tests etc.

Note:
- I don't think it's a good idea to expose this to our external API. Strings are better suited than internal types to ease use, but this doesn't apply to internal calls.

**Comment by ewjoachim** [comment]
(ping @mgu @samuelhamard any opinion ?)

**Comment by samuelhamard** [comment]
I think it could be good to use this everywhere we use versions as string outside the API, but currently we coudn't get the version string from the version object as `a.b.c` format

An other thing to check : 
- If the version string is gets from the file system it could be "001.3.02" so if you search the 1.3.2 version dir you have to browse all dirs to find a dir which match with this version. This mechanic can be little more difficult than get it from the original version string.

Note:
- I think it could be interesting to expose the version object to our external API if we want to permit others version format (for example version with letters "a.c.b") by overriding version class, but I not opposed to keep it internal.

**Comment by ewjoachim** [comment]
> If the version string is gets from the file system it could be "001.3.02" so if you search the 1.3.2 version dir you have to browse all dirs to find a dir which match with this version. This mechanic can be little more difficult than get it from the original version string.

Hm, right. But what if there's both a 01.2.3 and a 1.2.3 ?

> I think it could be interesting to expose the version object to our external API if we want to permit others version format (for example version with letters "a.c.b") by overriding version class, but I not opposed to keep it internal.

I'm not sure it's relevant to give a knob this powerful. Maybe rather "steal" the current implementation of distutils StrictVersion and vendor it as our own ?

**Comment by samuelhamard** [comment]
> Hm, right. But what if there's both a 01.2.3 and a 1.2.3 ?

I don't know but our current versionning system consider the the both as valid versions, so I think we have to answer this use case.

> I'm not sure it's relevant to give a knob this powerful. Maybe rather "steal" the current implementation of distutils StrictVersion and vendor it as our own ?

It's just an idea "thrown in the air", I'm not opposed to not expose this to our external API :upside_down_face:

**Comment by samuelhamard** [comment]
I think we can close this issue.
