### ISSUE TITLE
UnboundLocalError: local variable 'file_contents' referenced before assignment

### ISSUE THREAD

**Issue by alexdashkov** [peopledoc/septentrion#59]
If interpreter goes there: https://github.com/peopledoc/septentrion/blob/master/septentrion/cli.py#L42
On the line https://github.com/peopledoc/septentrion/blob/master/septentrion/cli.py#L49 it raises `UnboundLocalError`, but not the `exceptions.NoSeptentrionSection`.

**Comment by ewjoachim** [comment]
Indeed.

`return` instead of `pass` would solve it, I guess ?

**Comment by ewjoachim** [comment]
Do you want to fix it ?

**Comment by alexdashkov** [comment]
Yes, please. I'll take care of it on friday

**Comment by brunobord** [comment]
Formidable Service also impacted by this bug. If I'm reading this correctly, the patch would be:

```python
    if not value:
        try:
            file_contents, file = configuration.read_default_configuration_files()
        except exceptions.NoDefaultConfiguration:
            return
```

**Comment by brunobord** [comment]
won't we also need to assign a value to `default`?

and a more painful question: where and how do we write the correct tests?

**Comment by ewjoachim** [comment]
You mean assign a value to `ctx.default_map` ? Nah, the cli module already has decent defaults, this whole function only serves to override the defaults to the values of the config files. If we don't explicitely pass a config file, and there's no config file at the standard places, then there's nothing to do.


I'm wondering how come the tests never saw this: it should happen anytime we call septentrion without any configuration file, which is the case here:
https://github.com/peopledoc/septentrion/blob/master/tests/acceptance/test_cli.py

So, the minimal steps for me will be:
1. investigate why that test doesn't fail
2. add tests/unit/test_cli.py with a unittest:
  - Calls load_config() (with 2 stub params, you can use mocker.Mock() objects and value as a StringIO())
  - Mock configuration.read_default_configuration_files
  - Capture stdout via capsys
  - parametrized: no config file, default config, explicit config (through value), and for each of those, no septentrion section in the .ini file, or a septentrion section.
  - Check the value of ctx.default_map and stdout

A better way of fixing it: make a pure-python function that will encapsulate the same logic but will receive `value`, the ``configuration.read_default_configuration_files`` and the ``click.echo`` function as parameter, and returns the default_map or None. This function will behave independently from click.
It can be unit-tested much more simply.
Then change load_config to call this function. There should be no logic. This function can be moved to configuration.py.
At this point, I'm satisfied that the load_config function is not unit-tested, especially if it is acceptance-tested.

**Comment by brunobord** [comment]
> 1. investigate why that test doesn't fail

I can answer this one: because in the ``ALL_CONFIGURATION_FILES``, there's this value: ``"./setup.cfg"``. Which is the name of a file at the root of the project. As a consequence, the file is loaded.
